_target_: src.dp.model.diffusion_planner.Diffusion_Planner

# # Basic Settings
# name: "diffusion-planner-training"
# save_dir: "."

config:
  # Data Settings
  future_len: 80
  time_len: 11
  agent_state_dim: 9
  agent_num: 64
  # static_objects_state_dim: 10
  # static_objects_num: 5
  lane_len: 30
  lane_state_dim: 4
  lane_num: 256
  roadline_len: 30
  roadline_state_dim: 3
  roadline_num: 128
  static_map_len: 10
  static_map_state_dim: 3
  static_map_num: 20
  traffic_light_num: 20
  train_predictor: false

  # DataLoader Parameters
  augment_prob: 0.5
  normalization_file_path: ${paths.root_dir}/src/dp/normalization.json
  use_data_augment: true
  num_workers: 4
  pin_mem: true

  # Training Parameters
  seed: 3407
  train_epochs: 500
  save_utd: 20
  learning_rate: 5e-4
  warm_up_epoch: 5
  encoder_drop_path_rate: 0.1
  decoder_drop_path_rate: 0.1
  alpha_planning_loss: 1.0
  device: "cuda"
  use_ema: true

  # Model Parameters
  polyline_encoder_depth: 2
  encoder_depth: 3
  decoder_depth: 3
  num_heads: 8
  hidden_dim: 128
  local_attn_k: 16
  top_k_intention: 6
  num_modes: 6
  num_intention_points: 64
  diffusion_model_type: "x_start"

  # Decoder Parameters
  predicted_neighbor_num: 63
  action_len: 2
  rho_fixed: {1: 0.224, 3: 0.05}
  num_chunks: 8
  diffusion_steps: 10

  # Guidance Function
  guidance_fn: null

  # Validation Parameters
  step_len: 10
  val_open_loop: true
  val_closed_loop: false
  fast_wosac_metric: false
  n_rollout_closed_val: 32
  log_epoch: -1
  wosac_submission: 
    is_active: false
    method_name: "DP"
    authors: [Anonymous]
    affiliation: YOUR_AFFILIATION
    description: YOUR_DESCRIPTION
    method_link: YOUR_METHOD_LINK
    account_name: YOUR_ACCOUNT_NAME